### ISSUE TITLE
响应私聊消息抛出异常

### ISSUE THREAD

**Issue by FETE-CH** [frank-bots/cqhttp.Cyan#10]
接收到 `PrivateMessageEvent` 时 `return new PrivateMessageResponse(new Message("xxx"))` 抛出异常 
```
[15:46:50] [ERROR] 处理事件时发生未处理的异常Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: &. Path 'sition 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
   at cqhttp.Cyan.Events.CQResponses.Base.CQReplyMessageResponse..ctor(Message reply, Boolean auto_escape)
   at cqhttp.Cyan.Events.CQResponses.PrivateMessageResponse..ctor(Message reply, Boolean auto_escape)
   at QQBot.Program.EventHandle(CQApiClient api, CQEvent e) in /Users/fete/Documents/workspace/QQBot/Program.cs:line 43
   at cqhttp.Cyan.Instance.CQApiClient.__HandleEvent(CQEvent event_)
   at cqhttp.Cyan.Events.EventListener.HttpEventListener.ProcessContext(HttpListenerContext context),错误信息为Unexpected character encountered wparsing value: &. Path '', line 0, position 0.
```
看错误大概是 Json 解析错误，但是参数我试着传了 Json 格式文本还是有问题

**Comment by FETE-CH** [comment]
- 操作系统：Windows 10 1903
- 代码环境：.net core 3.0
- 酷Q： Air 版 5.15.3A(191014)
- 插件：coolq-http-api v4.12.2
- Cyan包：1.2.0

使用的是 Http 连接方式，可以收到 CoolQ 上报的数据，以下是部分代码
```c#
static CQResponse EventHandle(CQApiClient api, CQEvent e) {
            if (e is PrivateMessageEvent messageEvent) {
                Message message = messageEvent.message;
                string dataJson = message.raw_data_json;
                Console.WriteLine(dataJson);
                return new PrivateMessageResponse(new Message("新消息"));
            }
}
```

**Comment by frankli0324** [comment]
感谢。。。马上

**Comment by frankli0324** [comment]
dotnet add package cqhttp.Cyan --version 1.2.1-beta2

**Comment by frankli0324** [comment]
没有试试嘛？

**Comment by FETE-CH** [comment]
工作的时候没时间，刚才试了下，私聊消息回应没问题
